### ISSUE TITLE
Possible native SDK memory leak cleanup

### ISSUE THREAD

**Issue by FutureGUIs** [pushy-me/pushy-react-native#48]
Since there's not an Android Repo, not sure where else to report this, but running my app I see warnings about this code error:

`05-14 12:23:37.714 10461-10469/com.readytouchpos.smallstore E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.io.FileInputStream.<init>(FileInputStream.java:78)
        at java.io.FileReader.<init>(FileReader.java:42)
        at me.pushy.sdk.util.PushyIO.readFromFile(PushyIO.java:53)
        at me.pushy.sdk.util.PushyAuthentication.getDeviceCredentials(PushyAuthentication.java:42)
        at me.pushy.sdk.util.PushyServiceManager.start(PushyServiceManager.java:22)
        at me.pushy.sdk.Pushy.listen(Pushy.java:33)
        at me.pushy.sdk.react.modules.PushyModule.listen(PushyModule.java:103)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by pushy-me** [comment]
Hi @FutureGUIs,
Thanks so much for your report.

We've added a`.close()` call on all `BufferedReader` instances created by the SDK and released a new version.

Import version `1.0.55` of the Pushy Android SDK by updating the dependency in your `android/app/build.gradle`:

```
compile 'me.pushy:sdk:1.0.55'
```

Please let us know if the issue is resolved after updating the SDK.
