### ISSUE TITLE
How to use pushy in the case of android-building-from-source

### ISSUE THREAD

**Issue by amazingCoding** [pushy-me/pushy-react-native#65]
When I was developing, this was all well and good.
But when I use `. /gradlew assembleRelease` to install as an APK, the
Every time I want to open the APP with the push message, it will cause the APP to crash.
```
java.lang.RuntimeException: Could not invoke PushyModule.listen
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/~~mORTIVnn2wYVd6fH24K_5Q==/com.test.android-LEOH6MYEmRu44dcACGyc2g==/base.apk)
        at me.pushy.sdk.react.util.PushyMapUtils.convertJsonToMap(PushyMapUtils.java:26)
        at me.pushy.sdk.react.modules.PushyModule.onNotificationClicked(PushyModule.java:291)
        at me.pushy.sdk.react.modules.PushyModule.listen(PushyModule.java:111)
```

**Comment by pushy-me** [comment]
Hi @amazingCoding,
This error is most likely due to an outdated version of React Native in your project.

What is your current React Native dependency version? Please check your `package.json` and let us know what the `react-native` version is:

```
"react-native": "0.59.8"
```

**Comment by amazingCoding** [comment]
I am using this version： ```"react-native": "0.63.3"```
But strangely enough, when I was developing, it is fine.
It only crashes when it is released.

**Comment by pushy-me** [comment]
Hi @amazingCoding,
This might have to do with ProGuard. Can you please try building for release with `minifyEnabled false` in your app/build.gradle, under the `release` section, as follows:

https://github.com/pushy-me/pushy-demo-android/blob/master/app/build.gradle#L13-L15

**Comment by amazingCoding** [comment]
<img width="963" alt="截屏2021-06-15 上午1 43 38" src="https://user-images.githubusercontent.com/65453513/121935565-24fa7f80-cd7b-11eb-80ef-7ccbf06c077c.png">
I have actually turned off minifyEnabled.  

But unfortunately, the error still occurs.  

I checked the dex file in the APK and the method is real.

**Comment by amazingCoding** [comment]
> 嗨@amazingCoding，
> 这可能与ProGuard有关。您能否尝试`minifyEnabled false`在您的 app/build.gradle`release`部分下构建发布版本，如下所示：
> 
> https://github.com/pushy-me/pushy-demo-android/blob/a19dddd3320afb681b88f19100cc22a0ab6639da/app/build.gradle#L13-L15

I seem to have found the problem, but I don't know how to fix it.
I now realize that this project has been using the react-native source code from node_modules to compile

As stated here: https://doc.ebichu.cc/react-native/releases/0.23/docs/android-building-from-source.html
```
implementation project(':ReactAndroid')
```

When I change it back to use `implementation "com.facebook.react:react-native:+"`, the error doesn't appear.

I had to use the `implementation project(':ReactAndroid')` here, so how should I solve this problem?

**Comment by amazingCoding** [comment]
> Hi @amazingCoding,
> This might have to do with ProGuard. Can you please try building for release with `minifyEnabled false` in your app/build.gradle, under the `release` section, as follows:
> 
> https://github.com/pushy-me/pushy-demo-android/blob/a19dddd3320afb681b88f19100cc22a0ab6639da/app/build.gradle#L13-L15

I seem to have found the problem, but I don't know how to fix it.
I now realize that this project has been using the react-native source code from node_modules to compile

As stated here: https://doc.ebichu.cc/react-native/releases/0.23/docs/android-building-from-source.html
```
implementation project(':ReactAndroid')
```

When I change it back to use `implementation "com.facebook.react:react-native:+"`, the error doesn't appear.

I had to use the `implementation project(':ReactAndroid')` here, so how should I solve this problem?

**Comment by pushy-me** [comment]
Hi @amazingCoding,
It seems that your React Native source is missing a method called `putMap` in class `com/facebook/react/bridge/WritableMap`.

As per the [source code](https://github.com/facebook/react-native/blob/30ce8618b94b7e99d29e899ceceaf96f29abdeea/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableMap.java#L28), that method should definitely exist. Is it possible you are using outdated sources, or did you modify them in any way as to affect the availability of the `putMap` method?

Also, why are you building React Native from source? If you could simply revert to using the `implementation "com.facebook.react:react-native:+"` import , that would indeed resolve the issue.

Unfortunately, as this error does not have to do with our SDK specifically, but with your specific project/implementation, we are closing this issue.
